# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d86abb19-e812-4b2b-86b6-f7c4061e3b5d";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "bigdisk/safe/home";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "bigdisk/local/nix";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/342314a2-5347-4850-a605-d75512c60f20"; }
    ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}