- name: Install Pi-Hole
  become: true
  hosts:
    - pi_hole
  tasks:
    - name: Pre-install
      block:
        - name: Ensure required utilities are installed
          ansible.builtin.apt:
            name:
              - docker.io
              - docker-compose
            update_cache: yes
            cache_valid_time: 3600
            state: latest

        - name: Open firewall ports
          ansible.builtin.iptables:
            chain: INPUT
            protocol: "{{item.protocol}}"
            destination_port: "{{item.port}}"
            ctstate: NEW
            jump: ACCEPT
            comment: "{{item.comment}}"
          with_items:
            - port: 53
              protocol: tcp
              comment: Pi-Hole
            - port: 53
              protocol: udp
              comment: Pi-Hole
            - port: 67
              protocol: udp
              comment: Pi-Hole
            - port: 80
              protocol: tcp
              comment: Pi-Hole
            - port: 443
              protocol: tcp
              comment: Pi-Hole
            - port: 9100
              protocol: tcp
              comment: Node Exporter

        - name: Ensure Docker is running
          ansible.builtin.systemd:
            state: started
            name: docker
            enabled: yes

        - name: Ensure systemd-resolved is not running
          ansible.builtin.systemd:
            name: systemd-resolved
            state: stopped
            enabled: no

    - name: Install
      block:
        - name: Copy Pi Hole files
          ansible.builtin.copy:
            src: ./pi-hole
            dest: /srv
          delegate_to: "{{ inventory_hostname }}"

        - name: Write secret environment variables
          ansible.builtin.template:
            src: ./.env.j2
            dest: /srv/pi-hole/.env
            owner: root
            mode: "0600"

        - name: Create and start services
          community.docker.docker_compose:
            project_src: /srv/pi-hole
            pull: yes
            restarted: yes
            state: present
          register: output

        - name: Remove environment variables
          ansible.builtin.file:
            path: /srv/pi-hole/.env
            state: absent
