inputs:
{ config, pkgs, lib, ... }:
with lib; {
  imports = [
    inputs.self.nixosModules.contabo-vps
    inputs.self.nixosModules.server

    inputs.self.nixosModules.armqr
    inputs.self.nixosModules.auth-dns
    inputs.self.nixosModules.piwigo
  ];

  # Logrotate config build fail workaround
  # https://discourse.nixos.org/t/logrotate-config-fails-due-to-missing-group-30000/28501
  services.logrotate.checkConfig = false;

  astral = {
    ci.deploy-to = "173.212.242.107";
    tailscale.oneOffKey =
      "tskey-auth-kZQrDU5CNTRL-nWmsZRQDWshXHtvTUvBvth6tnPmUpAkHg";
    monitoring-node.scrapeTransport = "https";
  };

  networking = {
    hostName = "diluc";
    domain = "h.astrid.tech";

    firewall.allowedTCPPorts = [ 80 443 5432 ];
    interfaces.ens18.ipv6.addresses = [{
      address = "2a02:c207:2087:999::1";
      prefixLength = 128;
    }];

    bridges.bripa.interfaces = [ ];
    interfaces.bripa.ipv6.addresses = [{
      address = "2a02:c207:2087:999:1::1";
      prefixLength = 112;
    }];
  };

  time.timeZone = "Europe/Berlin";

  services.nginx = {
    enable = true;

    clientMaxBodySize = "16m";
    recommendedTlsSettings = true;
    recommendedOptimisation = true;
    recommendedGzipSettings = true;
  };

  services.postgresql = {
    enable = true;

    # Generated by PGConfig 3.1.0 (1d600ea0d1d79f13dd7ed686f9e2befc1fcf9226)
    # https://api.pgconfig.org/v1/tuning/get-config?format=conf&include_pgbadger=true&log_format=csvlog&max_connections=50&pg_version=15&environment_name=Mixed&total_ram=8GB&cpus=4&drive_type=SSD&arch=x86-64&os_type=linux
    settings = {
      listen_addresses = mkForce "*";
      ssl = "on";
      ssl_cert_file = "/var/lib/postgresql/server.crt";
      ssl_key_file = "/var/lib/postgresql/server.key";

      # Memory Configuration
      shared_buffers = "1GB";
      effective_cache_size = "3GB";
      work_mem = "16MB";
      maintenance_work_mem = "205MB";

      # Checkpoint Related Configuration
      min_wal_size = "2GB";
      checkpoint_completion_target = 0.9;
      wal_buffers = -1;

      # Storage Configuration
      random_page_cost = "1.1";
      effective_io_concurrency = "200";

      # Worker Processes Configuration
      max_worker_processes = 8;
      max_parallel_workers_per_gather = 2;
      max_parallel_workers = 2;

      # Adjust the minimum time to collect the data
      log_min_duration_statement = "10s";
      log_autovacuum_min_duration = 0;

      # Query stats
      shared_preload_libraries = "pg_stat_statements";
      "pg_stat_statements.max" = 10000;
      "pg_stat_statements.track" = "all";

      # Enable streaming replication as master
      wal_level = "logical";
      wal_log_hints = "on";
      max_wal_senders = 8;
      max_wal_size = "1GB";
      hot_standby = "on";
    };

    authentication = ''
      hostssl all akkoma 0.0.0.0/0 md5
      hostssl all akkoma ::/0 md5
    '';
  };

  virtualisation.vmVariant = {
    virtualisation.forwardPorts = [
      {
        from = "host";
        host.port = 2222;
        guest.port = 22;
      }
      {
        from = "host";
        guest.port = 80;
        host.port = 8080;
      }
      {
        from = "host";
        guest.port = 443;
        host.port = 8443;
      }
      {
        from = "host";
        proto = "udp";
        guest.port = 53;
        host.port = 8053;
      }
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ab29083b-5158-43d2-ab40-e3b40437bf31";
    fsType = "ext4";
  };
}
