HOME = .
config_diagnostics = 1

### Parameters for the root CA signing other CAs.
# openssl ca -config ... -name CA_root
[ CA_root ]
# Directory and file locations.
dir               = .
certs             = $dir/certs
crl_dir           = $dir/crl
new_certs_dir     = $dir/newcerts
database          = $dir/index.txt
serial            = $dir/serial
certificate       = $dir/certs/ca.crt

# For certificate revocation lists.
crlnumber         = $dir/crlnumber
crl               = $dir/crl/ca.crl
default_crl_days  = 1826 # 5 years

default_md        = sha256

default_days      = 1826 # 5 years
preserve          = no
policy            = policy_strict

[ policy_strict ]
# Intermediate certs must have the same organization name.
countryName             = optional
stateOrProvinceName     = optional
organizationName        = match
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

### Parameters for self-signing the CA.
# openssl req -config ... -section rootreq
[ rootreq ]
prompt              = no
distinguished_name  = rootreq_dn
string_mask         = utf8only
default_md          = sha256
x509_extensions     = v3_ca

[ rootreq_dn ]
# See <https://en.wikipedia.org/wiki/Certificate_signing_request>.
countryName                     = US
stateOrProvinceName             = California
localityName                    = San Francisco
0.organizationName              = astrid dot tech
organizationalUnitName          = DevSecAICatGoonGitChatOps
commonName                      = Astertificate Root Certificate R.1
emailAddress                    = astrid@astrid.tech

[ v3_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical, CA:true
keyUsage = critical, digitalSignature, cRLSign, keyCertSign

