# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ata_piix" "uhci_hcd" "hpsa" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "zfs" ]

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/c37da71a-ee60-4c7d-8845-01f9f2af4756";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    {
      device = "dpool/local/nix";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    {
      device = "dpool/safe/persist";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/594C-280C";
      fsType = "vfat";
    };

  swapDevices = [ ];

}
