{
 "title": "Minecraft, the Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"mc.astrid.tech:443\"}",
     "legendFormat": "1"
    },
    {
     "expr": "node_load5{instance=\"mc.astrid.tech:443\"}",
     "legendFormat": "5"
    },
    {
     "expr": "node_load15{instance=\"mc.astrid.tech:443\"}",
     "legendFormat": "15"
    }
   ]
  },
  {
   "title": "CPU/Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"mc.astrid.tech:443\"}",
     "legendFormat": "Active Memory"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"mc.astrid.tech:443\", mode!=\"idle\"}[3m])) by (cpu)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"mc.astrid.tech:443\", device=\"eth0\"}[1m])",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"mc.astrid.tech:443\", device=\"eth0\"}[1m])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"mc.astrid.tech:443\"}[1m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"mc.astrid.tech:443\"}[1m])",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Player Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Blocks Mined",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(blocks_mined[15m])) by (player)",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(player_online)", "legendFormat": "Players" }
   ]
  },
  {
   "title": "Man-Hours Wasted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "player_playtime / 20", "legendFormat": "{{player}}" }
   ]
  },
  {
   "title": "Players Online",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(player_online)" }
   ]
  },
  {
   "title": "Damage Taken",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    { "expr": "rate(damage_taken[15m])", "legendFormat": "{{player}}" }
   ]
  },
  {
   "title": "Movement",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(player_jumps[15m]))", "legendFormat": "Jumps" }
   ]
  },
  { "title": "Ancillary Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Caddy HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(caddy_http_requests_total{instance=\"mc.astrid.tech:443\"}[1m]))",
     "legendFormat": "HTTP Requests"
    },
    {
     "expr": "sum(rate(caddy_http_response_duration_seconds_sum{instance=\"mc.astrid.tech:443\"}[1m]))",
     "legendFormat": "Response Duration"
    }
   ]
  },
  {
   "title": "Dynmap Rendering",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dynmap_tile_render_statistics{file=\"TOTALS\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}