# Temporary configuration from BANANA because I don't have the thing yet ...
# TODO: figure out hardware when it gets here

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "bigdisk/enc/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "bigdisk/enc/nix";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0ED5-B12B";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "homie/enc/home";
      fsType = "zfs";
    };

  fileSystems."/data" =
    { device = "bigdisk/enc/data";
      fsType = "zfs";
    };

  fileSystems."/data/steam" =
    { device = "bigdisk/enc/data/steam";
      fsType = "zfs";
    };

  fileSystems."/var/lib/anbox/rootfs" =
    { device = "/nix/store/qhfx6fp5qsvlnkqf76n2awi8b6ajsh0r-android_amd64.img";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/var/lib/anbox/combined-rootfs" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/var/lib/anbox/combined-rootfs/cache" =
    { device = "/var/lib/anbox/cache";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/anbox/combined-rootfs/data" =
    { device = "/var/lib/anbox/data";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/lxd/shmounts" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/lxd/devlxd" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/lxd/storage-pools/default/containers/portalab" =
    { device = "homie/lxd/containers/portalab";
      fsType = "zfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.anbox0.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-6dc0473dbcf8.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-cc6feeeabe74.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.lxdbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.testbr.useDHCP = lib.mkDefault true;
  # networking.interfaces.vetha33d9adc.useDHCP = lib.mkDefault true;
  # networking.interfaces.virbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
