format = """
$git_branch\
$git_state\
$git_status\
$git_metrics \
$cmd_duration\
$line_break\
$username@$hostname $directory\
$python\
$character"""

# on large dirs (such as nixpkgs), command delegation may take a reeeeally long time.
# i prioritize responsiveness for shells so i will apply this very short
# "reacting-instantaneously" timeout upon it.
command_timeout = 50

[username]
format = "[$user]($style)"
show_always = true

[hostname]
format = "[$ssh_symbol$hostname]($style)"
ssh_only = false

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics] # line counts!
disabled = false 

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
