# This file generates a Github Actions runner from ci.nix.
{ self, lib, writeText, writeScriptBin, stdenvNoCC, yq }:
let
  workflowJSON = writeText "check-targets.json"
    (with lib; builtins.toJSON (makeGithubWorkflow ciGraph));

  workflowYAML = stdenvNoCC.mkDerivation {
    pname = "check-targets.yml";
    version = builtins.toString self.sourceInfo.lastModified;

    buildInputs = [ yq ];
    json = workflowJSON;

    phases = [ "installPhase" ];

    installPhase = ''
      (
        echo "# !!!!!!!! AUTO-GENERATED FILE, DO NOT MODIFY !!!!!!!!"
        echo "#"
        echo "# To modify CI behavior, you should edit /nix/ci.nix instead."
        echo "#"
        echo "# This file can be regenerated by the following command:"
        echo "#   $ nix run .#update-ci-workflow"
        echo
        yq -y -r --yml-out-ver 1.2 '.' "$json" 
      ) > "$out"
    '';
  };

  script = writeScriptBin "update-ci-workflow" ''
    root=$(git rev-parse --show-toplevel)
    dest="$root/.github/workflows/check-targets.yml"

    echo "Updating workflow file: $dest" >&2

    cp ${workflowYAML} "$dest"
  '';
in script
