# This file generates a Github Actions runner from ci.nix.
{ self, lib, writeScriptBin, runCommand, formats }:
let
  workflowYAML = (formats.yaml { }).generate "github-actions-workflow.yaml" self.lib.ci.workflow;

  workflowYAML' = runCommand "check-targets.yml" { inherit workflowYAML; } ''
    (
      echo "# !!!!!!!! AUTO-GENERATED FILE, DO NOT MODIFY !!!!!!!!"
      echo "#"
      echo "# To modify CI behavior, you should edit /nix/ci.nix instead."
      echo "#"
      echo "# This file can be regenerated by the following command:"
      echo "#   $ nix run .#update-ci-workflow"
      echo
      cat "$workflowYAML"
    ) > "$out"
  '';
in writeScriptBin "update-ci-workflow" ''
  set -euxo pipefail

  root=$(git rev-parse --show-toplevel)
  dest="$root/.github/workflows/check-targets.yml"

  echo "Updating workflow file: $dest" >&2

  cp ${workflowYAML'} "$dest"
''
