#!/bin/sh 

# See /usr/local/bin/ipv6_ndp_hack.py for more information.

. /etc/rc.subr 

name="ipv6_ndp_hack" 
rcvar=ipv6_ndp_hack_enable
pidfile="/tmp/ipv6_ndp_hack.pid"
command="/usr/sbin/daemon"
command_args="-p $pidfile /usr/local/bin/ipv6_ndp_hack.py"

load_rc_config $name 
run_rc_command "$1" 